### ISSUE TITLE
auto-pairs

### ISSUE THREAD

**Issue by binaryphile** [mutewinter/dot_vim#22]
say have you ever considered using a plugin which automatically completes quotes and other pairs?  I'm trying out jiangmiao/auto-pairs.  just started so i don't have a recommendation but I recently realized it's one of the features I miss from other editors.

**Comment by mutewinter** [comment]
https://github.com/Raimondi/delimitMate is in there and I like it. I've looked at other plugins, but I haven't found any so far that I like.

**Comment by binaryphile** [comment]
thanks for the pointer, i don't think i looked at that

**Comment by binaryphile** [comment]
also sorry for opening an issue, i couldn't find your email to ask the question directly.

**Comment by mutewinter** [comment]
> also sorry for opening an issue, i couldn't find your email to ask the question directly.

No worries! hi@mutewinter.com in the future
