### ISSUE TITLE
Cannot find color scheme 'jellybeans'

### ISSUE THREAD

**Issue by matochondrion** [mutewinter/dot_vim#31]
Hello,

I'm on OS X 10.12.6 and using nvim installed with Homebrew. After installing with:
```
git clone http://github.com/mutewinter/dot_vim.git ~/.config/nvim.
cd ~/.config/nvim.
```
I get the following error when starting nvim:

```
Error detected while processing /Users/rms/.config/nvim/config.vim:
line    9:
E185: Cannot find color scheme 'jellybeans'
Press ENTER or type command to continue
```

I've checked in the ~/.config/nvim/plug_plugins folder and I do see the `jellybeans.vim` directory.

Am I doing something wrong? 

Thank you.

**Comment by orliesaurus** [comment]
@matochondrion I have the same issue, did u find a fix?

**Comment by dalnk** [comment]
The way you fix it is creating a color directory right inside the /nvim/ folder, then move the jellybeans.vim there.

`cd ~/.config/nvim/
mkdir colors
mv plug_plugins/jellybeans.vim colors`

That should be it!
